server:
  port: 8012

spring:
  application:
    name: ConfigServer

  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/lsy0566/MyAppConfiguration.git
          username: lsy0566@naver.com
          password: 
          clone-on-start: true
        native:
          search-locations: file:///C:/Users/HPE/work/dev

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
