server:
  port: 8010

spring:
  application:
    name: DiscoveryService
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin


#Eureka Standalone Server
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/